## Orthogonal Projections in $\mathbf{R}^{n}$
#### The purpose of this notebook is to provide solutions for Exercise 3 (3.5) and Exercise 7 (Example 3.11) from Homework 3

In [3]:
import numpy as np

##### Exercise 3 

In [22]:
# Initialization of the basis matrix and the given vector 
B = np.array([
    [ 0,  1, -3, -1],
    [-1, -3,  4, -3],
    [ 2,  1,  1,  5],
    [ 0, -1,  2,  0],
    [ 2,  2,  1,  7]
])

x = np.array([-1, -9, -1, 4, 1])

if np.linalg.matrix_rank(B)!=4: 
    print("U does not form a basis")
    B=np.array([
    [ 0,  1, -3],
    [-1, -3,  4],
    [ 2,  1,  1],
    [ 0, -1,  2],
    [ 2,  2,  1]
])

# follow the steps of the book to compute the projection
BTB=B.T @ B
BTx=B.T @ x
# coefficients
lamCoeff=np.linalg.solve(BTB, BTx)
# orthogonal projection
proj = B @ lamCoeff
print(proj)
# projection matrix
P= B @ np.linalg.inv(BTB) @ B.T
print(P)
#basic verification
print(P @ x)
# Check orthogonality
res=x-proj
print(B.T @ res)
# Check Idempotence Property
print(np.allclose(P @ P, P))

U does not form a basis
[ 1. -5. -1. -2.  3.]
[[ 0.47619048 -0.28571429  0.19047619 -0.14285714 -0.33333333]
 [-0.28571429  0.68253968  0.06349206  0.28571429 -0.22222222]
 [ 0.19047619  0.06349206  0.92063492  0.14285714  0.11111111]
 [-0.14285714  0.28571429  0.14285714  0.14285714  0.        ]
 [-0.33333333 -0.22222222  0.11111111  0.          0.77777778]]
[ 1. -5. -1. -2.  3.]
[0. 0. 0.]
True


##### Exercise 7

In [9]:
# Initialization of the basis matrix and the given vector 
B=np.array([
    [1,0],
    [1,1],
    [1,2]
])
x=np.array([6,0,0])
# if the rank is not full, then we break the program as otherwise we don't have a basis
if np.linalg.matrix_rank(B) != 2:
     raise Exception("Not Full Rank")

# follow the steps of the book to compute the projection
BTB=B.T @ B
BTx=B.T @ x
# coefficients
lamCoeff=np.linalg.solve(BTB, BTx)
# orthogonal projection
proj = B @ lamCoeff
print(proj)
# projection matrix
P= B @ np.linalg.inv(BTB) @ B.T
print(P)


[ 5.  2. -1.]
[[ 0.83333333  0.33333333 -0.16666667]
 [ 0.33333333  0.33333333  0.33333333]
 [-0.16666667  0.33333333  0.83333333]]


In [15]:
#basic verification
print(P @ x)
# Check orthogonality
res=x-proj
print(B.T @ res)
# Check Idempotence Property
print(P @ P)

[ 5.  2. -1.]
[0. 0.]
[[ 0.83333333  0.33333333 -0.16666667]
 [ 0.33333333  0.33333333  0.33333333]
 [-0.16666667  0.33333333  0.83333333]]
