In [15]:
import numpy as np

In [14]:
A=np.array([[3,2,2],[2,3,-2]])
print(A)

[[ 3  2  2]
 [ 2  3 -2]]


In [16]:
ATA=A.T@A
eigenvals, eigenvecs=np.linalg.eig(ATA)
idx = np.argsort(np.real(eigenvals))[::-1]
eigvals = np.real(eigenvals[idx])
V = np.real(eigenvecs[:, idx])
print(V)

[[-7.07106781e-01  2.35702260e-01 -6.66666667e-01]
 [-7.07106781e-01 -2.35702260e-01  6.66666667e-01]
 [-4.59701721e-17  9.42809042e-01  3.33333333e-01]]


In [17]:
nonzero = eigvals > 1e-12 
singularvals = np.sqrt(eigvals[nonzero])
Sigma = np.zeros_like(A, dtype=float)
for i, s in enumerate(singularvals):
    Sigma[i, i] = s
print(Sigma)

[[5. 0. 0.]
 [0. 3. 0.]]


In [18]:
U = np.zeros((A.shape[0], len(singularvals)))
for i in range(len(singularvals)):
    U[:, i] = A @ V[:, i] / singularvals[i]
print(U)
     

[[-0.70710678  0.70710678]
 [-0.70710678 -0.70710678]]


In [19]:
A_eig=U @ Sigma @ V.T
print(np.allclose(A,A_eig))

True
