#### Exercise 6

In [2]:
import numpy as np

In [4]:
A=np.array([[1,0,1],[-2,1,0]])
print(A)

[[ 1  0  1]
 [-2  1  0]]


We first decompose A into its SVD using the np.linalg.svd() function ; 
Then we will reconstruct into A_svd and check if A_svd and A are the same matrices 

In [5]:
U,S,VT=np.linalg.svd(A)
Sigma=np.zeros((2,3))
Sigma[:2,:2]=np.diag(S)
A_svd=U@Sigma@VT
print(A_svd)

[[ 1.00000000e+00  0.00000000e+00  1.00000000e+00]
 [-2.00000000e+00  1.00000000e+00  1.66533454e-16]]


For the next part we will follow the steps of the book in Example 4.13 in order to compute the SVD from 
first principles using the np.linalg.eig() function
Specifically
1) Right Singular Vectors - we will find the eigenvectors of $A^{T}A$
2) Compute Singular Values and form $\Sigma$ - these will be the square roots of the eigenvalues of $A^{T}A$
3) Left Singular Vectors 

 Then we will reconstruct $_{eig}=U\Sigma V^{T}$ and compare it with $A_{svd}$

In [6]:
# Step 1:
ATA=A.T@A
eigenvals, eigenvecs=np.linalg.eig(ATA)
idx = np.argsort(np.real(eigenvals))[::-1]
eigvals = np.real(eigenvals[idx])
V = np.real(eigenvecs[:, idx])
print(V)

[[ 0.91287093  0.         -0.40824829]
 [-0.36514837  0.4472136  -0.81649658]
 [ 0.18257419  0.89442719  0.40824829]]


In [7]:
# Step 2:
nonzero = eigvals > 1e-12 
singularvals = np.sqrt(eigvals[nonzero])
Sigma = np.zeros_like(A, dtype=float)
for i, s in enumerate(singularvals):
    Sigma[i, i] = s
print(Sigma)

[[2.44948974 0.         0.        ]
 [0.         1.         0.        ]]


In [8]:
#Step 3:
U = np.zeros((A.shape[0], len(singularvals)))
for i in range(len(singularvals)):
    U[:, i] = A @ V[:, i] / singularvals[i]
print(U)

[[ 0.4472136   0.89442719]
 [-0.89442719  0.4472136 ]]


In [9]:
A_eig=U @ Sigma @ V.T
print(A_eig)

[[ 1.00000000e+00 -5.55111512e-17  1.00000000e+00]
 [-2.00000000e+00  1.00000000e+00 -5.55111512e-17]]


In [10]:
##Final Verification 

In [11]:
if np.allclose(A,A_svd) and np.allclose(A_svd,A_eig):
    print("Correct")

Correct
